kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.25.3@sha256:f52781bc0d7a19fb6c405c2af83abfeb311f130707a0e219175677e366cc45d1
    # Port forward 8080 to 30443 on the host
    extraPortMappings:
      # Port 30443 on the container
      - containerPort: 30443
        # Port 8080 on the host
        hostPort: 8080
        # TCP protocol
        protocol: TCP
        # Default listen address
        listenAddress: "0.0.0.0"
  - role: worker
    image: kindest/node:v1.25.3@sha256:f52781bc0d7a19fb6c405c2af83abfeb311f130707a0e219175677e366cc45d1